Feature: Aftersales error message validations

  @stubs @SBEValidations
  Scenario Outline: Validation of SBE error message
    Given a request is made to aftersales service with PNR "<PNR>"
    And with a CID value "<cid>"
    Then aftersales service responds with below details
      | ErrorCode | <ResponseCode> |
      | Message   | <ErrMessage>   |
      | Reason    | <Reason>       |
    Examples:
      | PNR   | cid   | ResponseCode   | Reason                      | ErrMessage                                                                                                                                                                                                                                                                       |
      | ABCDE | cid1  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid2  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid3  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid4  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid5  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid6  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid7  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid8  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid9  | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid10 | AFTERSALES_600 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry there has been an error that could not be resolved. Please start your search again later.                                                                                                                                                                                  |
      | ABCDE | cid11 | AFTERSALES_601 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry but we cannot display the details of your UK domestic journey at this time.                                                                                                                                                                                                |
      | ABCDE | cid12 | AFTERSALES_601 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry but we cannot display the details of your UK domestic journey at this time.                                                                                                                                                                                                |
      | ABCDE | cid13 | AFTERSALES_601 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry but we cannot display the details of your UK domestic journey at this time.                                                                                                                                                                                                |
      | ABCDE | cid14 | AFTERSALES_601 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry but we cannot display the details of your UK domestic journey at this time.                                                                                                                                                                                                |
      | ABCDE | cid15 | AFTERSALES_602 | SBE_EXTERNAL_SYSTEM_WARNING |                                                                                                                                                                                                                                                                                  |
      | ABCDE | cid16 | AFTERSALES_602 | SBE_EXTERNAL_SYSTEM_WARNING |                                                                                                                                                                                                                                                                                  |
      | ABCDE | cid17 | AFTERSALES_602 | SBE_EXTERNAL_SYSTEM_WARNING |                                                                                                                                                                                                                                                                                  |
      | ABCDE | cid18 | AFTERSALES_604 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry but we could not retrieve your booking information. Please ensure that the information you entered is correct and that you have entered the passenger's surname only. If the error persists, please contact our Eurostar Contact Centre                                    |
      | ABCDE | cid19 | AFTERSALES_605 | SBE_EXTERNAL_SYSTEM_WARNING | Sorry it seems we can't help with this boooking online, we'd suggest that you contact your original point of sale. <p>If you booked a "Train + Hotel" deal please <a href="http://travel.eurostar.com/trips/find" target="_blank">retrieve your booking here</a>. (SBE_302) </p> |
      | ABCDE | cid20 | AFTERSALES_606 | SBE_EXTERNAL_SYSTEM_WARNING | It is not possible to manage your booking online. Please call our customer service team on 03432 186 186 for assistance.                                                                                                                                                         |
      | ABCDE | cid21 | AFTERSALES_606 | SBE_EXTERNAL_SYSTEM_WARNING | It is not possible to manage your booking online. Please call our customer service team on 03432 186 186 for assistance.                                                                                                                                                         |

